#pragma once

#define IN						// Input
#define OUT						// Output
#define CLASS_API

#define BASE_CLASS
#define INTERFACE_CLASS
#define INHERITED_CLASS
#define ABSTRACT_CLASS

#define PUBLIC_FUNCTION
#define PRIVATE_FUNCTION
#define OPERATOR_OVERRIDE
#define INLINE_FUNCTION
#define STATIC_FUNCTION
#define STATIC_MEMBER_FUNCTION
#define OVERRIDE_FUNCTION
#define CONST_FUNCTION
#define CONST_MEMBER_FUNCTION
#define EXPLICIT_FUNCTION
#define VIRTUAL_FUNCTION
#define PURE_VIRTUAL_FUNCTION
#define MEMBER_FUNCTION
#define GLOBAL_FUNCTION

#define MAX_LINE_LENGTH		1024
#define LOG_BUFFER_SIZE		1024